# Generated by Django 5.1.1 on 2024-09-30 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_feetype"),
        ("learners", "0003_school_address_school_contact_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feetype",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="feetype",
            name="is_recurring",
        ),
        migrations.RemoveField(
            model_name="feetype",
            name="recurrence_period",
        ),
        migrations.AddField(
            model_name="feetype",
            name="payment_frequency",
            field=models.CharField(
                choices=[
                    ("WEEKLY", "Weekly"),
                    ("TERMLY", "Termly"),
                    ("ANNUALLY", "Annually"),
                ],
                default="TERMLY",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ClassFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="learners.grade"
                    ),
                ),
                (
                    "fee_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_fees",
                        to="finance.feetype",
                    ),
                ),
            ],
            options={
                "unique_together": {("fee_type", "class_group")},
            },
        ),
    ]
