# Generated by Django 5.1.1 on 2024-10-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_remove_feetype_amount_remove_feetype_is_recurring_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feetype",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
