# Generated by Django 5.1.1 on 2024-10-01 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0002_feetype_payment_frequency_alter_feetype_name"),
        ("finance", "0004_alter_feetype_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classfee",
            name="fee_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_fees",
                to="fees.feetype",
            ),
        ),
        migrations.DeleteModel(
            name="FeeType",
        ),
    ]
