# Generated by Django 5.1.1 on 2024-10-01 09:18

from django.db import migrations


def migrate_classfee_to_fees_feetype(apps, schema_editor):
    ClassFee = apps.get_model('finance', 'ClassFee')
    FeeType = apps.get_model('fees', 'FeeType')
    
    for class_fee in ClassFee.objects.all():
        try:
            new_fee_type = FeeType.objects.get(name=class_fee.fee_type.name)
            class_fee.fee_type = new_fee_type
            class_fee.save()
        except FeeType.DoesNotExist:
            # If the FeeType doesn't exist in the fees app, create it
            new_fee_type = FeeType.objects.create(
                name=class_fee.fee_type.name,
                description=class_fee.fee_type.description,
                payment_frequency=class_fee.fee_type.payment_frequency
            )
            class_fee.fee_type = new_fee_type
            class_fee.save()

class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_alter_classfee_fee_type_delete_feetype"),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_classfee_to_fees_feetype),
    ]
