# Generated by Django 5.1.1 on 2024-12-21 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('payment_frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('TERMLY', 'Termly'), ('ANNUALLY', 'Annually')], default='TERMLY', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', max_length=10)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learners.learnerregister')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.term')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feetype')),
            ],
            options={
                'unique_together': {('learner', 'year', 'fee_type')},
            },
        ),
    ]
