# Generated by Django 5.1.1 on 2024-10-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feetype",
            name="payment_frequency",
            field=models.CharField(
                choices=[
                    ("WEEKLY", "Weekly"),
                    ("TERMLY", "Termly"),
                    ("ANNUALLY", "Annually"),
                ],
                default="TERMLY",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feetype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
