# Generated by Django 5.1.1 on 2024-10-01 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0006_academicyear_alter_term_options_and_more"),
        ("fees", "0002_feetype_payment_frequency_alter_feetype_name"),
        ("learners", "0003_school_address_school_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feerecord",
            name="academic_year",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrator.academicyear",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="feerecord",
            unique_together={("learner", "academic_year", "fee_type")},
        ),
    ]
