# Generated by Django 5.1.1 on 2024-10-01 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0006_academicyear_alter_term_options_and_more"),
        ("fees", "0003_feerecord_academic_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feerecord",
            name="academic_year",
            field=models.ForeignKey(
                default="2023-2024",
                on_delete=django.db.models.deletion.CASCADE,
                to="administrator.academicyear",
            ),
        ),
    ]
