# Generated by Django 5.1.1 on 2025-01-25 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_attendance_learner_curriculum_grade_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authenticator', '0001_initial'),
        ('learners', '0005_learnerregister_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, to='authenticator.custompermission'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authenticator.role'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learners.school'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='from_grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='learners.grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='learner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learners.learnerregister'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='promoted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='to_grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='learners.grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authenticator.custompermission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authenticator.role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='promotion',
            unique_together={('learner', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
    ]
