# Generated by Django 5.1.1 on 2024-09-25 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticator", "0002_usersession"),
        ("learners", "0003_school_address_school_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="learners.school",
            ),
        ),
    ]
