# Generated by Django 5.1.1 on 2024-09-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authenticator', '0004_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompermission',
            options={'ordering': ['name'], 'verbose_name': 'Custom Permission', 'verbose_name_plural': 'Custom Permissions'},
        ),
        migrations.RemoveField(
            model_name='custompermission',
            name='content_type',
        ),
        migrations.AddField(
            model_name='custompermission',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
