# Generated by Django 5.1.1 on 2024-10-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0008_alter_promotion_unique_together_promotion_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='academic_year',
        ),
    ]
