# Generated by Django 5.0.3 on 2024-09-11 13:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamType",
            fields=[
                ("exam_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("Term 1", "Term 1"),
                            ("Term 2", "Term 2"),
                            ("Term 3", "Term 3"),
                        ],
                        default="Term 1",
                        max_length=100,
                    ),
                ),
                ("date_administered", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="LearnerTotalScore",
            fields=[
                (
                    "learner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="learners.learnerregister",
                    ),
                ),
                (
                    "total_score",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "exam_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exams.examtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("name", models.CharField(max_length=100)),
                ("subject_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "grades",
                    models.ManyToManyField(
                        related_name="subjects", to="learners.grade"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("date_examined", models.DateField(blank=True, null=True)),
                ("teacher_comment", models.TextField(blank=True)),
                (
                    "learner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_results",
                        to="learners.learnerregister",
                    ),
                ),
                (
                    "exam_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="exams.examtype",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_results",
                        to="exams.subject",
                    ),
                ),
            ],
            options={
                "unique_together": {("learner_id", "subject", "exam_type")},
            },
        ),
    ]
