# Generated by Django 5.1.1 on 2024-09-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('date_administered', models.DateField()),
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
