# Generated by Django 5.1.1 on 2024-09-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
