# Generated by Django 5.1.1 on 2024-09-07 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_subject'),
        ('learners', '0004_alter_feesmodel_learner_id_delete_learnermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('admission_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learners.learnerregister')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examtype')),
            ],
        ),
    ]
