# Generated by Django 5.1.1 on 2024-10-23 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_assignment_assignmentsubmission'),
        ('learners', '0004_learnerregister_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='grade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='learners.grade'),
        ),
    ]
