# Generated by Django 5.1.1 on 2024-09-07 10:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examresult'),
        ('learners', '0004_alter_feesmodel_learner_id_delete_learnermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='admission_number',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='math_mark',
        ),
        migrations.AddField(
            model_name='examresult',
            name='date_examined',
            field=models.DateField(blank=True, default=None, help_text='The date when the exam was taken', null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='learner_id',
            field=models.ForeignKey(default=None, help_text='The learner who took the exam', on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='learners.learnerregister'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='score',
            field=models.FloatField(help_text='The score obtained by the learner, between 0 and 100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='examresult',
            name='subject',
            field=models.ForeignKey(default=None, help_text='The subject for which the exam was taken', on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='exams.subject'),
        ),
    ]
