# Generated by Django 5.1.1 on 2024-09-07 11:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_examresult_admission_number_and_more'),
        ('learners', '0004_alter_feesmodel_learner_id_delete_learnermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerTotalScore',
            fields=[
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='learners.learnerregister')),
                ('total_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
