# Generated by Django 5.1.1 on 2024-10-23 13:24

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_assignment_allow_attachments_assignment_auto_grading_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
            ALTER TABLE exams_assignment 
            MODIFY description LONGTEXT,
            MODIFY prerequisites LONGTEXT,
            MODIFY learning_objectives LONGTEXT;
            
            ALTER TABLE exams_objectivequestion
            MODIFY question_text LONGTEXT;
            
            ALTER TABLE exams_feedbacktemplate
            MODIFY template_text LONGTEXT;
            ''',
            reverse_sql='''
            ALTER TABLE exams_assignment 
            MODIFY description TEXT,
            MODIFY prerequisites TEXT,
            MODIFY learning_objectives TEXT;
            
            ALTER TABLE exams_objectivequestion
            MODIFY question_text TEXT;
            
            ALTER TABLE exams_feedbacktemplate
            MODIFY template_text TEXT;
            '''
        ),
    ]
