# Generated by Django 5.1.1 on 2024-09-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_learnertotalscore'),
        ('learners', '0004_alter_feesmodel_learner_id_delete_learnermodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('learner_id', 'subject')},
        ),
    ]
