# Generated by Django 5.1.1 on 2024-09-07 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_examresult_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='exam_type',
            field=models.ForeignKey(blank=True, help_text='The exam name being recorded', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.examtype'),
        ),
    ]
