# Generated by Django 5.1.1 on 2024-10-23 13:29

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_assignment_learning_objectives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='learning_objectives',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='prerequisites',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='feedbacktemplate',
            name='template_text',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='objectivequestion',
            name='question_text',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
