# Generated by Django 5.0.3 on 2024-09-10 06:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0007_examresult_exam_type"),
        ("learners", "0010_remove_learnerregister_grade_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="examresult",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="learnertotalscore",
            name="exam_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="exams.examtype",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="grade",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="learners.grade",
            ),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="date_examined",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="exam_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="exams.examtype",
            ),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="learner_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_results",
                to="learners.learnerregister",
            ),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="score",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_results",
                to="exams.subject",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examresult",
            unique_together={("learner_id", "subject", "exam_type")},
        ),
    ]
