# Generated by Django 5.0.3 on 2024-09-10 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0008_alter_examresult_unique_together_and_more"),
        ("learners", "0011_alter_grade_grade_name_alter_learnerregister_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="grade",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="learners.grade",
            ),
        ),
    ]
