# Generated by Django 5.0.3 on 2024-09-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0009_alter_subject_grade"),
        ("learners", "0012_alter_grade_grade_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="grade",
        ),
        migrations.AddField(
            model_name="subject",
            name="grades",
            field=models.ManyToManyField(related_name="subjects", to="learners.grade"),
        ),
    ]
