# Generated by Django 5.0.3 on 2024-09-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0010_remove_subject_grade_subject_grades"),
    ]

    operations = [
        migrations.AddField(
            model_name="examresult",
            name="teacher_comment",
            field=models.TextField(blank=True),
        ),
    ]
