# Generated by Django 5.1.1 on 2024-09-26 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exams", "0002_behavioralassessment_extracurricularactivity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                ("date_of_birth", models.DateField()),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("date_joined", models.DateField(auto_now_add=True)),
                (
                    "subjects",
                    models.ManyToManyField(
                        related_name="subject_teachers", to="exams.subject"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
