# Generated by Django 5.1.1 on 2024-09-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
