# Generated by Django 5.1.1 on 2024-09-29 11:49

from django.db import migrations, models
import django.db.models.deletion


def migrate_subjects_to_subject_grades(apps, schema_editor):
    Teacher = apps.get_model('teachers', 'Teacher')
    TeacherSubjectGrade = apps.get_model('teachers', 'TeacherSubjectGrade')
    Grade = apps.get_model('learners', 'Grade')
    
    for teacher in Teacher.objects.all():
        for subject in teacher.subjects.all():
            for grade in Grade.objects.all():
                TeacherSubjectGrade.objects.create(teacher=teacher, subject=subject, grade=grade)


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_behavioralassessment_extracurricularactivity_and_more"),
        ("teachers", "0003_remove_teacher_date_joined_teachersubjectgrade_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learners.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'subject', 'grade')},
            },
        ),
        migrations.AddField(
            model_name="teacher",
            name="subject_grades",
            field=models.ManyToManyField(
                related_name="teachers",
                through="teachers.TeacherSubjectGrade",
                to="exams.subject",
            ),
        ),
        migrations.RunPython(migrate_subjects_to_subject_grades),
    ]
