# Generated by Django 5.1.1 on 2024-09-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0004_teacher_subject_grades_alter_teacher_subjects"),
    ]

    operations = [
        migrations.RunSQL(
            sql='SELECT 1;',  # This is a no-op SQL statement
            reverse_sql='SELECT 1;',
        ),
    ]
