# Generated by Django 5.1.1 on 2024-09-29 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_behavioralassessment_extracurricularactivity_and_more"),
        ("learners", "0003_school_address_school_contact_email_and_more"),
        ("teachers", "0005_auto_20240929_2207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachersubjectgrade",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="learners.grade"
            ),
        ),
    ]
