# Generated by Django 5.1.1 on 2024-09-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_behavioralassessment_extracurricularactivity_and_more"),
        ("teachers", "0006_remove_teacher_date_joined_alter_teacher_subjects_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="date_joined",
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subjects",
            field=models.ManyToManyField(
                related_name="teachers_direct", to="exams.subject"
            ),
        ),
    ]
