# Generated by Django 5.0.3 on 2024-09-12 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0001_initial"),
        ("learners", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="is_present",
        ),
        migrations.AddField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("late", "Late"),
                ],
                default="present",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="learner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_attendances",
                to="learners.learnerregister",
            ),
        ),
    ]
