# Generated by Django 5.1.1 on 2025-01-25 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('exams', '0001_initial'),
        ('learners', '0005_learnerregister_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='learner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin_attendances', to='learners.learnerregister'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculum',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='learners.grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subjects',
            field=models.ManyToManyField(related_name='curricula', to='exams.subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='admin_teachers', to='exams.subject'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='learners.grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='exams.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='administrator.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='administrator.year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='learners.grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='exams.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekschedule',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='week_schedules', to='administrator.term'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='year',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('learner', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('teacher', 'grade', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('year', 'term_number')},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('grade', 'day', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='weekschedule',
            unique_together={('term', 'week_number')},
        ),
    ]
