# Generated by Django 5.0.3 on 2024-09-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administrator",
            "0002_remove_attendance_grade_remove_attendance_is_present_and_more",
        ),
        ("exams", "0002_behavioralassessment_extracurricularactivity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="contact_number",
        ),
        migrations.AddField(
            model_name="teacher",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="is_class_teacher",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teacher",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="subjects",
            field=models.ManyToManyField(related_name="teachers", to="exams.subject"),
        ),
    ]
