# Generated by Django 5.1.1 on 2024-10-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_academicyear_alter_term_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['year', 'term_number']},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('year', 'term_number')},
        ),
        migrations.RemoveField(
            model_name='term',
            name='academic_year',
        ),
    ]
