# Generated by Django 5.1.1 on 2024-10-25 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_year_alter_term_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='administrator.year'),
        ),
    ]
