from django.urls import path
from .views import user_views, student_views, notification_views, auth_views, registration_views, StudentCoursesView, StudentAssignmentsView, StudentMessagesView, StudentResourcesView, StudentTimetableView, StudentAttendanceView, StudentExamResultsView, SchoolInfoView, LearnerInfoView, UserProfileView
from learners.views import LearnerProfileView
urlpatterns = [
    #path('auth/login/', auth_views.LoginView.as_view(), name='login'),
    path('auth/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('user/profile/', user_views.UserProfileView.as_view(), name='user-profile'),
    path('user/children/', user_views.UserChildrenView.as_view(), name='user-children'),
    path('student/profile/', student_views.StudentProfileView.as_view(), name='student-profile'),
    path('student/profile/<int:student_id>/', student_views.StudentProfileView.as_view(), name='student-profile-detail'),
    path('student/exam-results/', StudentExamResultsView.as_view(), name='student-exam-results'),
    path('student/exam-results/<int:student_id>/', StudentExamResultsView.as_view(), name='student-exam-results-detail'),
    path('student/attendance/', student_views.StudentAttendanceView.as_view(), name='student-attendance'),
    path('student/attendance/<int:student_id>/', student_views.StudentAttendanceView.as_view(), name='student-attendance-detail'),
    path('student/fees/', student_views.StudentFeesView.as_view(), name='student-fees'),
    path('student/fees/<int:student_id>/', student_views.StudentFeesView.as_view(), name='student-fees-detail'),
    path('student/payments/', student_views.StudentPaymentsView.as_view(), name='student-payments'),
    path('student/payments/<int:student_id>/', student_views.StudentPaymentsView.as_view(), name='student-payments-detail'),
    path('student/timetable/', student_views.StudentTimetableView.as_view(), name='student-timetable'),
    path('student/timetable/<int:student_id>/', student_views.StudentTimetableView.as_view(), name='student-timetable-detail'),
    path('student/dashboard/', student_views.StudentDashboardOverview.as_view(), name='student-dashboard'),
    path('student/dashboard/<int:student_id>/', student_views.StudentDashboardOverview.as_view(), name='parent-student-dashboard'),
    path('notifications/', notification_views.NotificationListView.as_view(), name='notification-list'),
    path('notifications/<int:pk>/mark-read/', notification_views.NotificationMarkReadView.as_view(), name='notification-mark-read'),
    path('student-parent/login/', auth_views.StudentParentLoginView.as_view(), name='student_parent_login'),
    path('student-parent/logout/', auth_views.StudentParentLogoutView.as_view(), name='student_parent_logout'),
    path('register/student/', registration_views.StudentRegistrationView.as_view(), name='student-registration'),
    path('register/parent/', registration_views.ParentRegistrationView.as_view(), name='parent-registration'),
    #path('class-levels/', registration_views.ClassLevelListView.as_view(), name='class-level-list'),
    path('grades/', registration_views.GradeListView.as_view(), name='grade-list'),
    path('students/', registration_views.StudentListView.as_view(), name='student-list'),
    # Updated URLs for the student dashboard
    path('student/courses/', StudentCoursesView.as_view(), name='student-courses'),
    path('student/courses/<int:student_id>/', StudentCoursesView.as_view(), name='student-courses-detail'),
    path('student/assignments/', StudentAssignmentsView.as_view(), name='student-assignments'),
    path('student/assignments/<int:student_id>/', StudentAssignmentsView.as_view(), name='student-assignments-detail'),
    path('student/messages/', StudentMessagesView.as_view(), name='student-messages'),
    path('student/messages/<int:student_id>/', StudentMessagesView.as_view(), name='student-messages-detail'),
    path('student/resources/', StudentResourcesView.as_view(), name='student-resources'),
    path('student/resources/<int:student_id>/', StudentResourcesView.as_view(), name='student-resources-detail'),
    path('student/timetable/', StudentTimetableView.as_view(), name='student-timetable'),
    path('student/timetable/<int:student_id>/', StudentTimetableView.as_view(), name='student-timetable-detail'),
    path('student/attendance/', StudentAttendanceView.as_view(), name='student-attendance'),
    path('student/attendance/<int:student_id>/', StudentAttendanceView.as_view(), name='student-attendance-detail'),
    path('school/info/', SchoolInfoView.as_view(), name='school-info'),
    path('learner/info/', LearnerInfoView.as_view(), name='learner-info'),
    #path('user/profile/', UserProfileView.as_view(), name='user-profile'),
    path('learner/profile/', LearnerProfileView.as_view(), name='learner-profile'),
]
