# Generated by Django 5.0.3 on 2024-09-11 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade_name",
                    models.CharField(
                        choices=[
                            ("Pre-Primary-1", "Pre-Primary-1"),
                            ("Pre-Primary-2", "Pre-Primary-2"),
                            ("Grade 1", "Grade 1"),
                            ("Grade 2", "Grade 2"),
                            ("Grade 3", "Grade 3"),
                            ("Grade 4", "Grade 4"),
                            ("Grade 5", "Grade 5"),
                            ("Grade 6", "Grade 6"),
                            ("Grade 7", "Grade 7"),
                            ("Grade 8", "Grade 8"),
                            ("Grade 9", "Grade 9"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("grade_description", models.TextField()),
                ("class_teacher_remark", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("principal_remark", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="LearnerRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("register_date", models.DateTimeField(auto_now_add=True)),
                ("learner_id", models.IntegerField(unique=True)),
                ("date_of_birth", models.DateField()),
                ("name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=100)),
                ("name_of_parent", models.CharField(default="Parent", max_length=100)),
                ("parent_contact", models.CharField(default="Contact", max_length=100)),
                (
                    "fee_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "maize_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "beans_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learners",
                        to="learners.grade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("register_date", models.DateTimeField(auto_now_add=True)),
                ("payment_id", models.IntegerField(default=0)),
                ("amount", models.IntegerField()),
                ("payment_type", models.CharField(max_length=100)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("credit_card", "Credit Card"),
                            ("mpesa", "Mpesa"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("received_by", models.CharField(max_length=100)),
                (
                    "learner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learners.learnerregister",
                    ),
                ),
            ],
        ),
    ]
