# Generated by Django 5.0.3 on 2024-09-14 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administrator",
            "0003_remove_teacher_contact_number_teacher_address_and_more",
        ),
        ("learners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learnerregister",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=100
            ),
        ),
        migrations.CreateModel(
            name="ClassLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level_name",
                    models.CharField(
                        choices=[
                            ("Pre-Primary-1", "Pre-Primary-1"),
                            ("Pre-Primary-2", "Pre-Primary-2"),
                            ("Grade 1", "Grade 1"),
                            ("Grade 2", "Grade 2"),
                            ("Grade 3", "Grade 3"),
                            ("Grade 4", "Grade 4"),
                            ("Grade 5", "Grade 5"),
                            ("Grade 6", "Grade 6"),
                            ("Grade 7", "Grade 7"),
                            ("Grade 8", "Grade 8"),
                            ("Grade 9", "Grade 9"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("level_description", models.TextField()),
                (
                    "class_representative_female",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="female_representative",
                        to="learners.learnerregister",
                    ),
                ),
                (
                    "class_representative_male",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="male_representative",
                        to="learners.learnerregister",
                    ),
                ),
                (
                    "class_teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="administrator.teacher",
                    ),
                ),
            ],
        ),
    ]
