# Generated by Django 5.1.1 on 2024-09-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerregister',
            name='name_of_parent',
            field=models.CharField(default='Parent', max_length=100),
        ),
        migrations.AddField(
            model_name='learnerregister',
            name='parent_contact',
            field=models.CharField(default='Contact', max_length=100),
        ),
    ]
