# Generated by Django 5.1.1 on 2025-01-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0002_remove_learnerregister_name_of_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='relationship_to_learner',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
