# Generated by Django 5.1.1 on 2024-09-06 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0002_learnerregister_name_of_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerregister',
            name='learner_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FeesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('payment_type', models.CharField(max_length=100)),
                ('received_by', models.CharField(max_length=100)),
                ('learner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learners.learnermodel')),
            ],
        ),
    ]
