# Generated by Django 5.1.1 on 2024-09-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learners", "0002_alter_learnerregister_gender_classlevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="address",
            field=models.TextField(default="Address"),
        ),
        migrations.AddField(
            model_name="school",
            name="contact_email",
            field=models.EmailField(default="Email", max_length=254),
        ),
        migrations.AddField(
            model_name="school",
            name="contact_phone",
            field=models.CharField(default="0712345678", max_length=20),
        ),
        migrations.AddField(
            model_name="school",
            name="logo",
            field=models.ImageField(
                default="static/src/img/masabaLogo.png", upload_to="school_logos/"
            ),
        ),
    ]
