# Generated by Django 5.1.1 on 2024-09-06 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0003_learnerregister_learner_id_feesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesmodel',
            name='learner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learners.learnerregister'),
        ),
        migrations.DeleteModel(
            name='LearnerModel',
        ),
    ]
