# Generated by Django 5.1.1 on 2025-01-18 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0003_parent_occupation_parent_relationship_to_learner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='relationship_to_learner',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian')], max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['email'], name='learners_pa_email_a4e737_idx'),
        ),
    ]
