# Generated by Django 5.0.3 on 2024-09-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learners", "0004_alter_feesmodel_learner_id_delete_learnermodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="feesmodel",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("credit_card", "Credit Card"),
                    ("mpesa", "Mpesa"),
                    ("other", "Other"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
