# Generated by Django 5.1.1 on 2025-01-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0004_alter_parent_relationship_to_learner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerregister',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('transferred', 'Transferred'), ('graduated', 'Graduated'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
