# Generated by Django 5.0.3 on 2024-09-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learners", "0006_learnerregister_grade_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learnerregister",
            name="grade_name",
            field=models.CharField(
                choices=[
                    ("Pre-Primary-1", "Pre-Primary-1"),
                    ("Pre-Primary-2", "Pre-Primary-2"),
                    ("grade1", "Grade 1"),
                    ("grade2", "Grade 2"),
                    ("grade3", "Grade 3"),
                    ("grade4", "Grade 4"),
                    ("grade5", "Grade 5"),
                    ("grade6", "Grade 6"),
                    ("grade7", "Grade 7"),
                    ("grade8", "Grade 8"),
                    ("grade9", "Grade 9"),
                ],
                default="Grade 1",
                max_length=100,
            ),
        ),
    ]
