# Generated by Django 5.0.3 on 2024-09-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learners", "0008_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="feesmodel",
            name="payment_id",
            field=models.IntegerField(default=0),
        ),
    ]
