# Generated by Django 5.0.3 on 2024-09-10 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learners", "0009_feesmodel_payment_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learnerregister",
            name="grade_name",
        ),
        migrations.AddField(
            model_name="learnerregister",
            name="grade",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learners",
                to="learners.grade",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="grade_name",
            field=models.CharField(
                choices=[
                    ("Pre-Primary-1", "Pre-Primary-1"),
                    ("Pre-Primary-2", "Pre-Primary-2"),
                    ("1", "Grade 1"),
                    ("2", "Grade 2"),
                    ("3", "Grade 3"),
                    ("4", "Grade 4"),
                    ("5", "Grade 5"),
                    ("6", "Grade 6"),
                    ("7", "Grade 7"),
                    ("8", "Grade 8"),
                    ("9", "Grade 9"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="learnerregister",
            name="learner_id",
            field=models.IntegerField(unique=True),
        ),
    ]
