# Generated by Django 5.0.3 on 2024-09-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learners", "0011_alter_grade_grade_name_alter_learnerregister_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="grade_name",
            field=models.CharField(
                choices=[
                    ("Pre-Primary-1", "Pre-Primary-1"),
                    ("Pre-Primary-2", "Pre-Primary-2"),
                    ("Grade 1", "Grade 1"),
                    ("Grade 2", "Grade 2"),
                    ("Grade 3", "Grade 3"),
                    ("Grade 4", "Grade 4"),
                    ("Grade 5", "Grade 5"),
                    ("Grade 6", "Grade 6"),
                    ("Grade 7", "Grade 7"),
                    ("Grade 8", "Grade 8"),
                    ("Grade 9", "Grade 9"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
