# Generated by Django 5.0.3 on 2024-09-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learners", "0012_alter_grade_grade_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("principal_remark", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="grade",
            name="class_teacher_remark",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="learnerregister",
            name="beans_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="learnerregister",
            name="fee_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="learnerregister",
            name="maize_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
