# Generated by Django 5.1.1 on 2025-01-18 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learners', '0002_remove_learnerregister_name_of_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentLearnerRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='learners.learnerregister')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='learners.parent')),
            ],
        ),
    ]
